### ISSUE TITLE
navigation

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#11]
## Value statement - a requirement, not a solution
As a user 
I want a clear navigation 
To be able to navigate sensibly between the pages

## Acceptance criteria
- [ ] I see several buttons at the bottom that take me to the different pages

## Tasks
- [ ] Create NavLink Navigation
- [ ] New page config-2

## Size
small
