### ISSUE TITLE
select door-system

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#13]
## Value statement - a requirement, not a solution
As a user 
I would like select the gate system
to configure the width and height accordingly

## Acceptance criteria
- [ ] I see a choice of the two door systems and my selection is included in the configuration

## Tasks
- [ ] Create select on config-page
- [ ] Adapt configuration accordingly

## Size
medium
