### ISSUE TITLE
select color for house-wall

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#14]
## Value statement - a requirement, not a solution
As a user 
I would like to select a color for my house wall
to choose later a matching door color

## Acceptance criteria
- [ ] I see a selection of colors and my selection is included in the configuration

## Tasks
- [ ] Create json-object with RAL-colors
- [ ] Create select on config2-page
- [ ] Adapt configuration accordingly

## Size
medium
