### ISSUE TITLE
additional articles on cart

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#17]
## Value statement - a requirement, not a solution
As a user
I would like to be shown the additional articles matching the selected door system, 
So that I can add them to the shopping cart 

## Acceptance criteria
- [ ] On Cart Page I see additional articles matching the selected door system
- [ ] I can add them to the shopping cart
- [ ] The positions are retained when the application is closed

## Tasks
- [ ] extend the existing json-object with additional articles
- [ ] Save cart in localStorage

## Size
medium
