### ISSUE TITLE
Unit- and component-tests

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#19]
## Value statement - a requirement, not a solution
As a developer 
I want to permanently test the app while developing
So that I notice when my code isn't working properly

## Acceptance criteria
- [ ] There are unit- and component-tests in the project
- [ ] Tests work correctly

## Tasks
- [ ] Check testing procedure
- [ ] Create tests

## Size
medium
