### ISSUE TITLE
simple config-page with inputs

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#2]
## Value statement - a requirement, not a solution
As a user
I would like to use input fields for gate width and gate height
to get the gate area displayed in square meters

## Acceptance criteria
- [ ] When starting the app I see 2 input fields for width and height and a text display of the calculated square meters.
- [ ] With each (meaningful) input into one of the two fields I see after Enter the newly calculated square meters

## Tasks
- [ ] Create a configuration page
- [ ] Creating two number input fields
- [ ] Creating a text display as feedback of the entered values

## Size
small

**Comment by mpagels** [comment]
Nice, small and clean. Very good. Looks good to me.
