### ISSUE TITLE
UI-UX design-page

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#25]
## Value statement - a requirement, not a solution
As a user
I want an intuitive and pleasant user interface
to enjoy working with the app

## Acceptance criteria
- [ ] Good UI/UX on design-page

## Tasks
- [ ] Optimize user experience
- [ ] Optimize graphic design

## Size
medium
