### ISSUE TITLE
new input field and draw on canvas

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#4]
## Value statement - a requirement, not a solution
As a user
I would also like to be able to enter the gate radius and see the gate opening graphically
 to have a better idea

## Acceptance criteria
- [ ] In addition to width and height, I can now also enter the archway radius.
- [ ] With every (sensible) input I now also see a graphic representation of the gate opening in the correct ratio.

## Tasks
- [ ] Create another input field for archway radius.
- [ ] Create a graphical display (canvas) as a representation of the gate opening according to the entered values.

## Size
medium

**Comment by Kheirah** [comment]
An incremental step towards a valuable feature, I like it!
