### ISSUE TITLE
Simple shopping cart function

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#6]
## Value statement - a requirement, not a solution
As a user
I would like to use a shopping cart
to select items for my garage door

## Acceptance criteria
- [ ] By clicking on a button on the existing configuration page I get to the shopping page
- [ ] I see items from which I can choose.
- [ ] I see a shopping cart with the selected items.

## Tasks
- [ ] Create a simple shopping page
- [ ] Create a button on the Config page
- [ ] Create article data in json format and display them
- [ ] Create a shopping cart and display the selected items

## Size
medium
