### ISSUE TITLE
local storage

### ISSUE THREAD

**Issue by FrankOelsch** [FrankOelsch/capstone-project#9]
## Value statement - a requirement, not a solution
As a user
I would like my entered measuring data to be saved 
So that i do not have to enter it again 

## Acceptance criteria
- [ ] When the app is opened again, the entered data for width, height and radius are available

## Tasks
- [ ] Create a json-object
- [ ] Save it in localStorage
- [ ] Load it from localStorage

## Size
small
